### PR TITLE
Make `AiService` global

### LINKED ISSUE #7: Make `AiServices` class global
`AiService` class is responsible for managing the AI connection and storing document's embeddings.

This class also connects to `AiPreference` to check for other updates.

The object of this class should remain global, live for every session of JabRef.

Currently, `AiService` lives in `AiChatTab` (or actually I have even moved it to `EntryEditor`). This is not right, because objects of this class reset on library change.

### PR DESCRIPTION
**Pull request by InAnYan**
Closes #7.

I made the `AiSevice` live inside
`JabRefGUI`. It lives alongside the `PreferenceService`, and other classes that are often referenced in constructors.

Yes, I can't find the appropriate word for "classes that are often used in constructors", so I hope the reviewers will understand what I mean by looking at the changes (yes, I understand that's not the right way to behave).

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

### CODE REVIEW

**Review by koppor — COMMENTED** [review]
This is kind of the "old" way - superseded by https://github.com/JabRef/jabref/pull/11342, but 11342 will be part of the next release... so, let's move on with this.

**Comment by InAnYan** [comment]
Okay, I checked the files again and came to conclusion:
- Where you used a `private final` field and initialized it in constructor, I did the same for `AiService`.
- Where you used an `@Inject private final`, I used it.

**Comment by koppor** [comment]
@InAnYan 🤣🤣 - I think, you found out what `@Contracts` are offered by JabRef (these can be injecgted; the others cannot) - See https://github.com/koppor/jabref/pull/687#issuecomment-2132827543 for some more links.

I created an internal issue (https://github.com/JabRef/jabref-issue-melting-pot/issues/440) to label all "contracts" as such. - If you have capacity, you can do it using your experienced gained. IMHO, these are 3 to 5 classes being contracts or are there more?

**Comment by koppor** [comment]
Other thing: Delete the merged branches. You can do it after merging, have [refined github browser plugin](https://github.com/refined-github/refined-github) doing it automatically, or use [the branch overview](https://github.com/InAnYan/jabref/branches) now and then to delete.

**Pull request merged**
